"""'addumidadeagregadoemassadeagua'

Revision ID: 5dc1315310cd
Revises: 7d17f68e9dfe
Create Date: 2021-09-23 01:32:38.954507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc1315310cd'
down_revision = '7d17f68e9dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dosagem_piloto', sa.Column('a_massa_umida', sa.Integer(), nullable=True))
    op.add_column('dosagem_pobre', sa.Column('a_massa_umida', sa.Integer(), nullable=True))
    op.add_column('dosagem_pobre', sa.Column('umidade_agregado', sa.Integer(), nullable=True))
    op.add_column('dosagem_rico', sa.Column('a_massa_umida', sa.Integer(), nullable=True))
    op.add_column('dosagem_rico', sa.Column('umidade_agregado', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dosagem_rico', 'umidade_agregado')
    op.drop_column('dosagem_rico', 'a_massa_umida')
    op.drop_column('dosagem_pobre', 'umidade_agregado')
    op.drop_column('dosagem_pobre', 'a_massa_umida')
    op.drop_column('dosagem_piloto', 'a_massa_umida')
    # ### end Alembic commands ###
