"""add_umidade_agregado

Revision ID: 7d17f68e9dfe
Revises: 159aa59a240b
Create Date: 2021-09-22 03:17:05.574127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d17f68e9dfe'
down_revision = '159aa59a240b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dosagem_piloto', sa.Column('umidade_agregado', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dosagem_piloto', 'umidade_agregado')
    # ### end Alembic commands ###
