"""'ColocandoRelationship'

Revision ID: a62b9690df62
Revises: b2eb9bbb370f
Create Date: 2021-09-21 02:44:34.779121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62b9690df62'
down_revision = 'b2eb9bbb370f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dosagem_piloto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alfa', sa.Integer(), nullable=True),
    sa.Column('c_unitario', sa.Integer(), nullable=True),
    sa.Column('a_unitario', sa.Integer(), nullable=True),
    sa.Column('b_unitario', sa.Integer(), nullable=True),
    sa.Column('c_massa', sa.Integer(), nullable=True),
    sa.Column('a_massa', sa.Integer(), nullable=True),
    sa.Column('b_massa', sa.Integer(), nullable=True),
    sa.Column('c_acr', sa.Integer(), nullable=True),
    sa.Column('a_acr', sa.Integer(), nullable=True),
    sa.Column('agua', sa.Integer(), nullable=True),
    sa.Column('ensaio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ensaio_id'], ['ensaios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dosagem_piloto')
    # ### end Alembic commands ###
